export const endpoints = {
  myself: "/rest/api/3/myself",
  projectSearch: "/rest/api/3/project/search",
  project: (projectKey: string) => `/rest/api/3/project/${encodeURIComponent(projectKey)}`,
  projectVersions: (projectKey: string) => `/rest/api/3/project/${encodeURIComponent(projectKey)}/versions`,
  projectComponents: (projectKey: string) => `/rest/api/3/project/${encodeURIComponent(projectKey)}/components`,
  boardList: "/rest/agile/1.0/board",
  board: (boardId: number) => `/rest/agile/1.0/board/${boardId}`,
  boardSprints: (boardId: number) => `/rest/agile/1.0/board/${boardId}/sprint`,
  sprint: (sprintId: number) => `/rest/agile/1.0/sprint/${sprintId}`,
  sprintIssues: (sprintId: number) => `/rest/agile/1.0/sprint/${sprintId}/issue`,
  issueSearchJql: "/rest/api/3/search/jql",
  issueSearchLegacy: "/rest/api/3/search",
  createIssue: "/rest/api/3/issue",
  issue: (issueKey: string) => `/rest/api/3/issue/${encodeURIComponent(issueKey)}`,
  issueComments: (issueKey: string) => `/rest/api/3/issue/${encodeURIComponent(issueKey)}/comment`,
  issueTransitions: (issueKey: string) => `/rest/api/3/issue/${encodeURIComponent(issueKey)}/transitions`,
  issueAssignee: (issueKey: string) => `/rest/api/3/issue/${encodeURIComponent(issueKey)}/assignee`,
  issueLink: "/rest/api/3/issueLink",
  userSearch: "/rest/api/3/user/search",
  version: "/rest/api/3/version",
  versionById: (versionId: string) => `/rest/api/3/version/${encodeURIComponent(versionId)}`,
  component: "/rest/api/3/component",
  componentById: (componentId: string) => `/rest/api/3/component/${encodeURIComponent(componentId)}`,
  createSprint: "/rest/agile/1.0/sprint",
  createMeta: "/rest/api/3/issue/createmeta",
  plans: "/rest/api/3/plans/plan",
  plan: (planId: number) => `/rest/api/3/plans/plan/${planId}`
};
